"""
Django settings for aims_project project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os

# Load environment variables from .env file
try:
    from dotenv import load_dotenv
    load_dotenv()
except ImportError:
    print("Warning: python-dotenv not installed. Please run: pip install python-dotenv")
    # Will use os.getenv() with fallback values

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-fallback-key-change-in-production')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True').lower() in ['true', '1', 'yes', 'on']

# Convert comma-separated ALLOWED_HOSTS to list
ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '*').split(',') if os.getenv('ALLOWED_HOSTS', '*') != '*' else ['*']

# =============================================================
# Reverse Proxy / Path-based Routing
# ใช้เมื่อ deploy ผ่าน IIS + ARR (Path-based Routing)
# Dev: FORCE_SCRIPT_NAME=''  (ไม่ต้องตั้ง)
# Prod: FORCE_SCRIPT_NAME=/aims
# =============================================================
FORCE_SCRIPT_NAME = os.getenv('FORCE_SCRIPT_NAME', '')
USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Secure Cookies — เปิดอัตโนมัติเมื่อ DEBUG=False (production)
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG

# CSRF Trusted Origins — เพิ่ม domain จริงใน .env
# Dev: http://localhost:8001
# Prod: https://lib.npu.ac.th
CSRF_TRUSTED_ORIGINS = [
    o.strip()
    for o in os.getenv('CSRF_TRUSTED_ORIGINS', 'http://localhost:8001').split(',')
    if o.strip()
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'corsheaders',

    #Custom Apps
    'accounts',
    'dashboard',
    'dashboard_system',  # Executive Dashboard System v2.0
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'aims_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'aims_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': os.getenv('DB_ENGINE', 'django.db.backends.mysql'),
        'NAME': os.getenv('DB_NAME', 'aims'),
        'USER': os.getenv('DB_USER', 'admin_e'),
        'PASSWORD': os.getenv('DB_PASSWORD', ''),
        'HOST': os.getenv('DB_HOST', '202.29.55.213'),
        'PORT': os.getenv('DB_PORT', '3306'),
        'OPTIONS': {
            'charset': 'utf8mb4',
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'"
        }
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

# Dev: /static/   Prod: /aims/static/  (ตั้งผ่าน .env)
STATIC_URL = os.getenv('STATIC_URL', '/static/')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom User Model
AUTH_USER_MODEL = 'accounts.User'

# Authentication Backends
AUTHENTICATION_BACKENDS = [
    'accounts.authentication.LDAPBackend',
    'django.contrib.auth.backends.ModelBackend',  # ยังคงรองรับการ login แบบปกติของ Django
]

# LDAP API Settings
LDAP_API_URL = os.getenv('LDAP_API_URL', 'https://api.npu.ac.th/v2/ldap/auth_and_get_personnel/')
LDAP_API_TOKEN = os.getenv('LDAP_API_TOKEN', 'your-ldap-token-here')

# Login URL
LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/accounts/portal/'
LOGOUT_REDIRECT_URL = '/accounts/login/'

# Google Sheets Integration
GOOGLE_SHEETS_CREDENTIALS_FILE = os.getenv('GOOGLE_SHEETS_CREDENTIALS_FILE', 
                                           os.path.join(BASE_DIR, 'credentials', 'control-room-440116-7cd01a8c02bd.json'))
GOOGLE_SHEETS_SPREADSHEET_ID = os.getenv('GOOGLE_SHEETS_SPREADSHEET_ID', '1Z64aIUqfH2SMc__m3brPINUE6kqgQq_ii0OC8uXiae8')

# CORS Settings
CORS_ALLOWED_ORIGINS = os.getenv('CORS_ALLOWED_ORIGINS', 'http://localhost:8000').split(',')
CORS_ALLOW_ALL_ORIGINS = os.getenv('DEBUG', 'True').lower() in ['true', '1', 'yes', 'on']  # Only in debug mode
# หรือระบุโดเมนที่อนุญาตเฉพาะ
# CORS_ALLOWED_ORIGINS = [
#     "https://example.com",
#     "https://sub.example.com",
# ]

# เพิ่ม security headers
SECURE_CROSS_ORIGIN_OPENER_POLICY = 'same-origin'

# JWT Settings for SSO
JWT_SECRET_KEY = os.getenv('JWT_SECRET_KEY', SECRET_KEY)
JWT_ALGORITHM = 'HS256'
JWT_EXPIRATION_HOURS = int(os.getenv('JWT_EXPIRATION_HOURS', '8'))

# SSO Settings
SSO_COOKIE_NAME = 'sso_token'
SSO_COOKIE_DOMAIN = os.getenv('SSO_COOKIE_DOMAIN', None)  # None = current domain only
SSO_COOKIE_SECURE = os.getenv('SSO_COOKIE_SECURE', 'False').lower() in ['true', '1', 'yes', 'on']
SSO_COOKIE_HTTPONLY = True  # ป้องกัน XSS