# Generated by Django 5.2.4 on 2026-05-06 22:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(choices=[('staff_info', 'ข้อมูลบุคลากร (staff_info)'), ('students_info', 'ข้อมูลนักศึกษา (students_info)')], max_length=50)),
                ('status', models.CharField(choices=[('running', 'กำลังดำเนินการ'), ('success', 'สำเร็จ'), ('failed', 'ล้มเหลว')], default='running', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('records_before', models.IntegerField(default=0)),
                ('records_after', models.IntegerField(default=0)),
                ('records_synced', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('triggered_by', models.CharField(default='manual', max_length=20)),
                ('triggered_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sync_logs',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['table_name', 'started_at'], name='sync_logs_table_n_7a1397_idx'), models.Index(fields=['status'], name='sync_logs_status_e8f5ef_idx')],
            },
        ),
    ]
