# Generated by Django 5.2.4 on 2025-08-05 08:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-last_login', 'username'], 'verbose_name': 'ผู้ใช้งาน', 'verbose_name_plural': 'ผู้ใช้งาน'},
        ),
        migrations.AddField(
            model_name='user',
            name='is_ldap_user',
            field=models.BooleanField(default=True, verbose_name='ผู้ใช้ LDAP'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_activity',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='กิจกรรมล่าสุด'),
        ),
        migrations.AddField(
            model_name='user',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='หมายเหตุ'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='เบอร์โทรศัพท์'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.URLField(blank=True, null=True, verbose_name='รูปโปรไฟล์'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('staff_admin', 'Staff Admin'), ('academic_service', 'Academic Service'), ('read_only', 'Read Only')], default='academic_service', max_length=20, verbose_name='บทบาทผู้ใช้'),
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='หน่วยงาน'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_academic_service',
            field=models.BooleanField(default=False, verbose_name='สำนักวิทยบริการ'),
        ),
        migrations.AlterField(
            model_name='user',
            name='ldap_data',
            field=models.JSONField(blank=True, null=True, verbose_name='ข้อมูล LDAP'),
        ),
        migrations.AlterField(
            model_name='user',
            name='personnel_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='รหัสบุคลากร'),
        ),
        migrations.AlterField(
            model_name='user',
            name='personnel_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ประเภทบุคลากร'),
        ),
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ตำแหน่ง'),
        ),
    ]
