# Generated by Django 4.2.11 on 2025-08-05 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_options_user_is_ldap_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='division',
            field=models.CharField(blank=True, choices=[('', '--กรุณาเลือกแผนก--'), ('information_services', 'แผนกบริการสารสนเทศฯ'), ('technical', 'แผนกเทคนิคฯ'), ('policy_planning', 'แผนกนโยบายและแผน'), ('general_admin', 'แผนกบริหารงานทั่วไป')], max_length=50, null=True, verbose_name='แผนก'),
        ),
    ]
