# Generated by Django 4.2.11 on 2025-08-05 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_division'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='system_access',
            field=models.JSONField(blank=True, default=dict, help_text='ระบบที่ผู้ใช้สามารถเข้าใช้งานได้', verbose_name='ระบบที่เข้าได้'),
        ),
        migrations.AddField(
            model_name='user',
            name='system_roles',
            field=models.JSONField(blank=True, default=dict, help_text='บทบาทของผู้ใช้ในแต่ละระบบ', verbose_name='บทบาทในแต่ละระบบ'),
        ),
    ]
