# Generated by Django 4.2.11 on 2026-02-20 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_system_access_user_system_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='วันที่อนุมัติ'),
        ),
        migrations.AddField(
            model_name='user',
            name='approved_by',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='อนุมัติโดย'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='อนุมัติโดย Admin'),
        ),
    ]
